### ISSUE TITLE
Dimensionality reduction and feature selection

### ISSUE THREAD

**Issue by omarbenites** [rasbt/stat451-machine-learning-fs20#1]
Hello Sebastian,

First of all, thanks for your great lectures!, I am currently learning a lot from your youtube playlist about this course, each lecture is very well explained.
On the other hand, I would like to ask you if you have lecture videos about dimensionality reduction and feature selection?.  I see you have some slides in the 2019 version (Github repo https://github.com/rasbt/stat479-machine-learning-fs19) but there are no video lectures about those topics in the 2020 version.  

Again, thanks for your lectures!.

Best regards,

**Comment by rasbt** [comment]
Thanks for the kind words and your interest in this! Unfortunately, I didn't get around to record them ... the semester ended a but sooner than anticipated. Or let's say I was a bit slower than I anticipated wrt to the lecture timeline. I may record these lectures one day, maybe end of summer or next semester. I can't make a firm promise though
